[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F/M7F (with FPU)

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

runner = "probe-rs run --chip stm32l475vgtx"

[env]
DEFMT_LOG = "info"



