[package]
name = "vm"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2021"

[lib]
name = "interpreter"
path = "src/lib.rs"

[features]
default = ["std"]
std = []

[[bin]]
name = "vm"
path = "src/main.rs"

[dependencies]

[lints.clippy]
pedantic = "deny"
